version: "3.8"
services:
  rocketmq-nameserver-a:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-nameserver-a
    ports:
      - "9876:9876"
    volumes:
      - ./data/nameserver-a/logs:/opt/logs
    networks:
      rmq:
        aliases:
          - rocketmq-nameserver-a
    command: mqnamesrv

  rocketmq-broker-a:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-broker-a
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    volumes:
      - ./data/broker-a/logs:/opt/logs
      - ./data/broker-a/store:/opt/store
      - ./data/broker-a/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      NAMESRV_ADDR: "rocketmq-nameserver-a:9876"
      JAVA_OPT_EXT: "-Xms512M -Xmx512M -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rocketmq-nameserver-a
    networks:
      rmq:
        aliases:
          - rocketmq-broker-a

  rocketmq-broker-b:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-broker-b
    ports:
      - "10929:10909"
      - "10931:10911"
      - "10932:10912"
    volumes:
      - ./data/broker-b/logs:/opt/logs
      - ./data/broker-b/store:/opt/store
      - ./data/broker-b/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      NAMESRV_ADDR: "rocketmq-nameserver-a:9876"
      JAVA_OPT_EXT: "-Xms512M -Xmx512M -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rocketmq-nameserver-a
    networks:
      rmq:
        aliases:
          - rocketmq-broker-b

  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    ports:
      - "8080:8080"
    depends_on:
      - rocketmq-nameserver-a
    environment:
      NAMESRV_ADDR: "rocketmq-nameserver-a:9876"
      JAVA_OPTS: " -Drocketmq.namesrv.addr=rocketmq-nameserver-a:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    networks:
      rmq:
        aliases:
          - rocketmq-dashboard


  notification-service:
    container_name: notification-service
    #image: notification-service-image:0.0.1-SNAPSHOT
    build:
      dockerfile: ./docker/notification-service.Dockerfile
    depends_on:
      - rocketmq-nameserver-a
    ports:
      - "8081:8081"
    networks:
      - rmq

  order-service:
    container_name: order-service
    #image: order-service-image:0.0.1-SNAPSHOT
    build:
      dockerfile: ./docker/order-service.Dockerfile
    depends_on:
      - rocketmq-nameserver-a
    ports:
      - "8083:8083"
    networks:
      - rmq

networks:
  rmq:
    name: rmq
    driver: bridge
