version: "3.8"
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.6
    ports:
      - "2181:2181"
      - "8090:8080"
    restart: always
    networks:
      - zknetwork


  rocketmq-nameserver-a:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-nameserver-a
    ports:
      - "9876:9876"
    volumes:
      - ./data/nameserver-a/logs:/home/rocketmq/logs
    command: mqnamesrv
    networks:
      - rmq

  rocketmq-nameserver-b:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-nameserver-b
    ports:
      - "9877:9876"
    volumes:
      - ./data/nameserver-b/logs:/home/rocketmq/logs
    command: mqnamesrv
    networks:
      - rmq

  rocketmq-broker-a:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-broker-a
    restart: always
    volumes:
      - ./data/broker-a/logs:/opt/logs
      - ./data/broker-a/store:/opt/store
      - ./data/broker-a/conf/broker.conf:/etc/rocketmq/broker.conf
    ports:
      - "10910:10910"
    environment:
      NAMESRV_ADDR: "rocketmq-nameserver-a:9876;rocketmq-nameserver-b:9876"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rocketmq-nameserver-a
      - rocketmq-nameserver-b
    networks:
      - rmq

  rocketmq-broker-a-s:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-broker-a-s
    restart: always
    volumes:
      - ./data/broker-a-s/logs:/opt/logs
      - ./data/broker-a-s/store:/opt/store
      - ./data/broker-a-s/conf/broker.conf:/etc/rocketmq/broker.conf
    ports:
      - "10911:10911"
    environment:
      NAMESRV_ADDR: "rocketmq-nameserver-a:9876;rocketmq-nameserver-b:9876"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rocketmq-nameserver-a
      - rocketmq-nameserver-b
    networks:
      - rmq

  rocketmq-broker-b:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-broker-b
    restart: always
    volumes:
      - ./data/broker-b/logs:/opt/logs
      - ./data/broker-b/store:/opt/store
      - ./data/broker-b/conf/broker.conf:/etc/rocketmq/broker.conf
    ports:
      - "10920:10920"
    environment:
      NAMESRV_ADDR: "rocketmq-nameserver-a:9876;rocketmq-nameserver-b:9876"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rocketmq-nameserver-a
      - rocketmq-nameserver-b
    networks:
      - rmq

  rocketmq-broker-b-s:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-broker-b-s
    restart: always
    volumes:
      - ./data/broker-b-s/logs:/opt/logs
      - ./data/broker-b-s/store:/opt/store
      - ./data/broker-b-s/conf/broker.conf:/etc/rocketmq/broker.conf
    ports:
      - "10921:10921"
    environment:
      NAMESRV_ADDR: "rocketmq-nameserver-a:9876;rocketmq-nameserver-b:9876"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rocketmq-nameserver-a
      - rocketmq-nameserver-b
    networks:
      - rmq

  notification-service-1:
    container_name: notification-service-1
    build:
      dockerfile: ./docker/notification-service.Dockerfile
    depends_on:
      - rocketmq-nameserver-a
      - rocketmq-nameserver-b
      - zookeeper
    ports:
      - "8081:8081"
    volumes:
      - ./logs/notification-service-1:/home/logs
    networks:
      - rmq
      - zknetwork

  notification-service-2:
    container_name: notification-service-2
    build:
      dockerfile: ./docker/notification-service.Dockerfile
    depends_on:
      - rocketmq-nameserver-a
      - rocketmq-nameserver-b
      - zookeeper
    ports:
      - "8082:8081"
    volumes:
      - ./logs/notification-service-2:/home/logs
    networks:
      - rmq
      - zknetwork

  order-service-1:
    container_name: order-service-1
    build:
      dockerfile: ./docker/order-service.Dockerfile
    depends_on:
      - rocketmq-nameserver-a
      - rocketmq-nameserver-b
      - zookeeper
    ports:
      - "8083:8083"
    volumes:
      - ./logs:/home/logs
    networks:
      - rmq
      - zknetwork

  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    container_name: rocketmq-dashboard
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - rocketmq-nameserver-a
      - rocketmq-nameserver-b
    environment:
      NAMESRV_ADDR: "rocketmq-nameserver-a:9876;rocketmq-nameserver-b:9876"
      JAVA_OPTS_EXT: "-server -Xms128m -Xmx128m -Xmn128m -Drocketmq.namesrv.addr=rocketmq-nameserver-a:9876;rocketmq-nameserver-b:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    networks:
      - rmq

networks:
  rmq:
    name: rmq
    driver: bridge
  zknetwork:
    name: zknetwork
    driver: bridge
