version: "3.8"
services:
  rocketmq-nameserver:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-nameserver
    ports:
      - "9876:9876"
    volumes:
      - ./logs:/opt/logs
      - ./store:/opt/store
    networks:
      rmq:
        aliases:
          - rocketmq-nameserver
    command: mqnamesrv

  rocketmq-broker:
    image: foxiswho/rocketmq:4.8.0
    container_name: rocketmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
    volumes:
      - ./logs:/opt/logs
      - ./store:/opt/store
      - ./conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      NAMESRV_ADDR: "rocketmq-nameserver:9876"
      JAVA_OPT_EXT: "-Xms512M -Xmx512M -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rocketmq-nameserver
    networks:
      rmq:
        aliases:
          - rocketmq-broker

  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    ports:
      - "8080:8080"
    depends_on:
      - rocketmq-nameserver
    environment:
      NAMESRV_ADDR: "rocketmq-nameserver:9876"
      JAVA_OPTS: " -Drocketmq.namesrv.addr=rocketmq-nameserver:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    networks:
      rmq:
        aliases:
          - rocketmq-dashboard


  notification-service:
    container_name: notification-service
    #image: notification-service-image:0.0.1-SNAPSHOT
    build:
      dockerfile: ./docker/notification-service.Dockerfile
    depends_on:
      - rocketmq-nameserver
    ports:
      - "8081:8081"
    networks:
      - rmq

  order-service:
    container_name: order-service
    #image: order-service-image:0.0.1-SNAPSHOT
    build:
      dockerfile: ./docker/order-service.Dockerfile
    depends_on:
      - rocketmq-nameserver
    ports:
      - "8083:8083"
    networks:
      - rmq

networks:
  rmq:
    name: rmq
    driver: bridge
