server.port: 8083

spring:
  application.name: order-service
  cloud:
    zookeeper:
      connect-string: zookeeper:2181
      discovery:
        enabled: true

rocketmq:
  name-server: rocketmq-nameserver-a:9876
  producer:
    group: order-service-producer-group
    send-message-timeout: 300000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-async-failed: 0
    retry-next-server: true
    retry-times-when-send-failed: 2

logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
